version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Yekaterinburg"
    commit-message:
      prefix: "Go module"
    labels:
      - "dependencies"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Yekaterinburg"
    commit-message:
      prefix: "Github actions"
    labels:
      - "dependencies"
