name: Create release

on:
  pull_request:
    types:
      - closed

jobs:
  release-on-push:
    if: github.event.pull_request.merged == true
    name: Generate release and tag
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
          tag_prefix: v
          use_github_release_notes: true